name = "ObjectPools"
uuid = "658cac36-ff0f-48ad-967c-110375d98c9d"
authors = ["Christoph Ortner <christohortner@gmail.com> and contributors"]
version = "0.0.2"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"

[compat]
DataStructures = "0.18"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
