name = "ObjectPools"
uuid = "658cac36-ff0f-48ad-967c-110375d98c9d"
authors = ["Christoph Ortner <christohortner@gmail.com> and contributors"]
version = "0.3.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StrideArrays = "d1fa6d79-ef01-42a6-86c9-f7c551f8593b"

[compat]
DataStructures = "0.18"
StrideArrays = "0.1.24"
julia = "1.8"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
